mahgits script update, unique users for each host and refactoring

diff --git a/scripts/mahgits b/scripts/mahgits
--- a/scripts/mahgits
+++ b/scripts/mahgits
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Simple tool to add remotes for most used git hosts for the same repo
+# Simple tool to manage repos across various git hosts
 # for now only github, gitlab and bitbucket 
 
 # Disable file globbing
@@ -17,6 +17,7 @@ gitlabAPI='https://gitlab.com/api/v4/projects'
 # Flags
 isInit=0
 force=0
+uniqueUser=0
 pushOne=0
 pushAll=0
 rRemotes=0
@@ -24,52 +25,59 @@ createRepos=0
 
 # remote name followed by the url
 remotes="github git@github.com gitlab git@gitlab.com bitbucket git@bitbucket.org"
-curRemotes="$(git remote show)"
+curRemotes=""
+remoteNames=""
 
 getRemoteNames() {
 	rout=""
 	# shellcheck disable=SC2086
 	set -- $remotes # word splitting
 	while : ; do
-		[ -z "$1" ] || [ -z "$2" ] && break; 
+		[ -z "$1" ] || [ -z "$2" ] && break;
 		rout="$rout $1"
 		shift 2
 	done
-	printf "%s\n" "${rout# }"
+	printf "%s" "${rout# }"
 }
 
-remoteNames="$(getRemoteNames)"
-
-inColor() {
-	color=""
-	case "$1" in
-		# 0 = black
-		1) color="\033[1;31m" ;; # red
-		2) color="\033[1;32m" ;; # green
-		3) color="\033[1;33m" ;; # yellow
-		4) color="\033[1;34m" ;; # blue
-		5) color="\033[1;35m" ;; # purple
-		6) color="\033[1;36m" ;; # teal
-		7) color="\033[1;37m" ;; # white
-		*) printf "Invalid option %s \nColor is not set\n" "$1" >&2 ;;
-	esac
-	printf "%b" "$color$2\033[0m"
-}
+# Disable color if not outputing to terminal
+if [ -t 1 ]; then
+	inColor() {
+		color=""
+		case "$1" in
+			# 0 = black
+			1) color="\033[1;31m" ;; # red
+			2) color="\033[1;32m" ;; # green
+			3) color="\033[1;33m" ;; # yellow
+			4) color="\033[1;34m" ;; # blue
+			5) color="\033[1;35m" ;; # purple
+			6) color="\033[1;36m" ;; # teal
+			7) color="\033[1;37m" ;; # white
+			*) printf "Invalid option %s \nColor is not set\n" "$1" >&2 ;;
+		esac
+		printf "%b" "$color$2\033[0m"
+	}
+else
+	inColor() {
+		printf "%s" "$2"
+	}
+fi
 
 usage() {
-	printf "usage: mahgits [--init [-f] ] | [-a] | [-b branch] | [-r] | [--create [-f] ]
+	printf "usage: mahgits [--init [-f] [-u]] | [-a] | [-b branch] | [-r] | [--create [-f] ]
 	--init   \tSet all new remotes in current git repo
 	--create \tWill create the remote repos and set api tokens file
 	-f       \tForces Init, overwriting remotes, api tokens file rewrite
+	-u       \tInit each remote with an unique username for each service
 	-r       \tRemoves remotes from git repo
 	-a       \tPush all branches to all remotes
-	-b branch\tPush one branch to all remotes\n"
+	-b branch\tPush one branch to all remotes\n" >&2
 }
 
 ask() {
 	askInput=""
 	while [ "$askInput" != "y" ] && [ "$askInput" != "n" ]; do
-		printf "%b (y | n): " "$2" 
+		printf "%b (y | n): " "$2" >&2
 		read -r askInput 
 		[ -z "$askInput" ] && askInput="$3"
 	done
@@ -77,7 +85,7 @@ ask() {
 	eval "$1=$askInput"
 }
 
-chechSSHAgent() {
+checkSSHAgent() {
 	if ! pidof ssh-agent > /dev/null ; then
 		printf "%b\n" "$(inColor 2 'Starting ssh-agent on current shell')"
 		eval "$(ssh-agent)"
@@ -94,7 +102,7 @@ checkRemotes() {
 		done
 
 		[ "$missingThisOne" -eq 1 ] && {
-			printf "Missing %b remote\n" "$(inColor 1 "$r")" >&2
+			printf "Missing %b remote\n" "$(inColor 1 "$r")"
 			isMissing=1
 		}
 	done
@@ -106,7 +114,6 @@ checkRemotes() {
 }
 
 checkRemotesToAdd() {
-
 	for r in $remoteNames; do
 		missingRemote=1
 		for cr in $curRemotes; do
@@ -123,25 +130,78 @@ checkRemotesToAdd() {
 }
 
 initRemotes() {
-	
 	initRemotes=""
 	# shellcheck disable=SC2015
 	[ "$force" -eq 1 ] && initRemotes="$remoteNames" || checkRemotesToAdd 
 	initRemotes="${initRemotes# }"
-	printf "To add remotes '%b'\n" "$(inColor 1 "$initRemotes")"
+	printf "To add remotes '%b'\n" "$(inColor 2 "$initRemotes")"
 
-	okinput=0
-	answer=""
-	while [ $okinput -eq 0 ]; do
-		printf "Enter the ssh user: " 
-		read -r user
-		printf "Enter the repository name: "
-		read -r repo
+	githubRepo=""
+	gitlabRepo=""
+	bitbucketRepo=""
 
-		repoinfo=":$user/$repo"
-		ask "answer" "user: $user\nrepo: $repo\nConfirm?"
-		[ "$answer" = "y" ] && okinput=1;
-	done
+	if [ "$uniqueUser" -eq 1 ]; then
+		if echo "$initRemotes" | grep -q "\bgithub\b"; then
+			okInput=0
+			answer=""
+			while [ $okInput -eq 0 ]; do
+				printf "Enter the username ("$(inColor 3 'github')"): " >&2
+				read -r user
+				printf "Enter the repository name ("$(inColor 3 'github')"): " >&2
+				read -r repo
+
+				githubRepo=":$user/$repo"
+				ask "answer" "user: "$(inColor 4 "$user")"\nrepo: "$(inColor 4 "$repo")"\n"$(inColor 1 'Confirm?')""
+				[ "$answer" = "y" ] && okInput=1;
+			done
+		fi
+
+		if echo "$initRemotes" | grep -q "\bgitlab\b"; then
+			okInput=0
+			answer=""
+			while [ $okInput -eq 0 ]; do
+				printf "Enter the username ("$(inColor 3 'gitlab')"): " >&2
+				read -r user
+				printf "Enter the repository name ("$(inColor 3 'gitlab')"): " >&2
+				read -r repo
+
+				gitlabRepo=":$user/$repo"
+				ask "answer" "user: "$(inColor 4 "$user")"\nrepo: "$(inColor 4 "$repo")"\n"$(inColor 1 'Confirm?')""
+				[ "$answer" = "y" ] && okInput=1;
+			done
+		fi
+
+		if echo "$initRemotes" | grep -q "\bbitbucket\b"; then
+			okInput=0
+			answer=""
+			while [ $okInput -eq 0 ]; do
+				printf "Enter the username ("$(inColor 3 'bitbucket')"): " >&2
+				read -r user
+				printf "Enter the repository name ("$(inColor 3 'bitbucket')"): " >&2
+				read -r repo
+
+				bitbucketRepo=":$user/$repo"
+				ask "answer" "user: "$(inColor 4 "$user")"\nrepo: "$(inColor 4 "$repo")"\n"$(inColor 1 'Confirm?')""
+				[ "$answer" = "y" ] && okInput=1;
+			done
+		fi
+	else
+		okInput=0
+		answer=""
+		while [ $okInput -eq 0 ]; do
+			printf "Enter the username: " >&2
+			read -r user
+			printf "Enter the repository name: " >&2
+			read -r repo
+
+			tmpRepo=":$user/$repo"
+			ask "answer" "user: "$(inColor 4 "$user")"\nrepo: "$(inColor 4 "$repo")"\n"$(inColor 1 'Confirm?')""
+			[ "$answer" = "y" ] && okInput=1;
+		done
+		githubRepo="$tmpRepo"
+		gitlabRepo="$tmpRepo"
+		bitbucketRepo="$tmpRepo"
+	fi
 
 	# shellcheck disable=SC2086
 	set -- $remotes # word splitting
@@ -149,32 +209,40 @@ initRemotes() {
 		[ -z "$1" ] || [ -z "$2" ] && break;
 
 		if ! echo "$initRemotes" | grep -q "\b$1\b"; then
-			printf "Skipping remote %b\n" "$(inColor 1 "$r")"
+			printf "Remote %b already set, skipping...\n" "$(inColor 1 "$1")"
 			shift 2
 			continue
 		fi
 
-		remotetoadd="$1 $2$repoinfo"
-		if [ -z "$force" ]; then
-			printf "Adding remote '%b'\n" "$(inColor 1 "$remotetoadd")"
-			# shellcheck disable=SC2086
-			git remote add $remotetoadd # word splitting 
-		else
-			printf "Force Adding remote '%b'\n" "$(inColor 1 "$remotetoadd")"
+		#hax, lazy to change all the func
+		case "$1" in
+			github) repoInfo="$githubRepo" ;;
+			gitlab) repoInfo="$gitlabRepo" ;;
+			bitbucket) repoInfo="$bitbucketRepo" ;;
+		esac
+
+		remoteToAdd="$1 $2$repoInfo"
+		if [ "$force" -eq 1 ]; then
+			printf "Force Adding remote '%b'\n" "$(inColor 1 "$remoteToAdd")"
 			git remote remove "$1"
 			# shellcheck disable=SC2086
-			git remote add $remotetoadd # word splitting 
+			git remote add $remoteToAdd # word splitting 
+		else
+			printf "Adding remote '%b'\n" "$(inColor 5 "$remoteToAdd")"
+			# shellcheck disable=SC2086
+			git remote add $remoteToAdd # word splitting 
 		fi
 		shift 2
 	done
-	printf "%b\n%b\n" "$(inColor 2 'Remotes added')" "$(inColor 4 'To create the remote repos if needed use --create')"
-	exit 0
+	printf "%b\n" "$(inColor 2 'Remotes added')"
+	printf "%b\n" "$(inColor 4 'To create the remote repos if needed use --create')" >&2
 }
 
 pushAllBranches() {
 	checkRemotes
+	checkSSHAgent
 	for r in $remoteNames; do
-		printf "Pushing all branches to remote: %b\n" "$(inColor 1 "$r")"
+		printf "Pushing all branches to remote: %b\n" "$(inColor 3 "$r")"
 		git push --all "$r"
 	done
 	printf "%b\n" "$(inColor 2 'Pushed all branches to all remotes')"
@@ -184,7 +252,7 @@ removeRemotes() {
 	for r in $remoteNames; do
 		for cr in $curRemotes; do
 			[ "$r" = "$cr" ] && {
-				printf "Removing '%b' remote\n" "$(inColor 1 "$r")" >&2
+				printf "Removing '%b' remote\n" "$(inColor 1 "$r")"
 				git remote remove "$r"
 			}
 		done
@@ -192,12 +260,13 @@ removeRemotes() {
 }
 
 pushBranches() {
-	[ "$rRemotes" -eq 1 ] && removeRemotes && exit 0
+	[ "$rRemotes" -eq 1 ] && { removeRemotes;  exit 0; }
 	checkRemotes
+	checkSSHAgent
 	branches="$(git branch | tr -d '* ')"
 	btopush=""	
 	for b in $branches; do
-		ask "answer" "Push branch: '$(inColor 1 "$b")' ? [y]" "y"	
+		ask "answer" "Push branch: '$(inColor 5 "$b")' ? [y]" "y"	
 		[ "$answer" = "y" ] && btopush="$btopush $b"
 	done	
 	btopush="${btopush# }"
@@ -208,36 +277,35 @@ pushBranches() {
 	fi
 
 	for r in $remoteNames; do
-		printf "Pushing '%b' to remote '%b'\n" "$(inColor 1 "$btopush")" "$(inColor 3 "$r")"
+		printf "Pushing '%b' to remote '%b'\n" "$(inColor 3 "$btopush")" "$(inColor 2 "$r")"
 		# shellcheck disable=SC2086
 		git push "$r" $btopush # word splitting
 	done
-	printf "%b '%b' %b\n" "$(inColor 2 'Pushed branches:')" "$(inColor 1 "$btopush")" "$(inColor 2 'to all remotes')"
+	printf "%b '%b' %b\n" "$(inColor 2 'Pushed branches:')" "$(inColor 3 "$btopush")" "$(inColor 2 'to all remotes')"
 }
 
 pushOneBranch() {
 	checkRemotes
-	# branches="$(git branch | tr -d '* ')"
+	checkSSHAgent
 	if ! git branch | tr -d '* ' | grep -q "\b$branchToPush\b"; then
 		printf "The branch %b does not exist\n" "$(inColor 1 "$branchToPush")" >&2
 		exit 1
 	fi
 	
 	for r in $remoteNames; do
-		printf "Pushing branch %b to remote %b" "$(inColor 1 "$branchToPush")" "$(inColor 2 "$r")"
+		printf "Pushing branch %b to remote %b" "$(inColor 2 "$branchToPush")" "$(inColor 2 "$r")"
 		git push "$r" "$branchToPush"
 	done
 	printf "Pushed branch %b to all remotes" "$(inColor 2 "$branchToPush")"
 }
 
 createAuthFile() {
-
 	authFileExists=0
 	[ -s "$authFile" ] && authFileExists=1 
 	[ "$authFileExists" -ne 1 ] || [ "$force" -eq 1 ] && {
 		[ "$authFileExists" -eq 1 ] && {
 			if file "$authFile" | grep -q GPG; then
-				printf "Decrypt current file in place\n"
+				printf "Decrypt current file in place\n" >&2
 				sleep 3
 				if tmp="$(gpg -d "$authFile" 2> /dev/null)"; then
 					echo "$tmp" > "$authFile"
@@ -245,12 +313,13 @@ createAuthFile() {
 				else
 					answer=""
 					ask "answer" "Failed to decrypt, $(inColor 1 'overwrite current file with defaults?') [n]" "n"
-					[ "$answer" = "n" ] && printf "Aborting...\n" && exit 1 
+					[ "$answer" = "n" ] && printf "Aborting...\n" >&2 && exit 1 
 				fi
 			fi
 		}
-		printf "Creating mahgits auth file at %b\n" "$(inColor 1 "$authFile")" >&2
-		printf "# This file will be encrypted
+		printf "Creating mahgits auth file at %b\n" "$(inColor 2 "$authFile")"
+
+printf "# This file will be encrypted
 # Insert the tokens, example: github	f0fda58630310a6dd91a7d8f0a4ceda2
 
 # Get the PAT at https://github.com/settings/tokens
@@ -265,9 +334,10 @@ gitlab		PAT
 # Get the app password at https://bitbucket.org/account/settings/app-passwords/
 # Check the permissions: Repositories: Admin
 
-bitbucket	APP_PASSWORD\n" > "$authFile"
-	}
+bitbucket	APP_PASSWORD
+" > "$authFile"
 
+	}
 }
 
 createGithubRepo() {
@@ -292,7 +362,7 @@ createGithubRepo() {
 }
 
 createBitbucketRepo() {
-	projKeyFile='.git/bitbucketProjKey'
+	[ -z "$GIT_DIR" ] && projKeyFile='.git/bitbucketProjKey' || projKeyFile="$GIT_DIR/bitbucketProjKey"
 	repoInfo="$(git remote get-url bitbucket)"
 	repoInfo="${repoInfo#*:}"
 
@@ -306,18 +376,19 @@ createBitbucketRepo() {
 		printf "Using bitbucket project key stored at: %b\n" "$(inColor 3 "$(realpath "$projKeyFile")")"
 		projectKey="$(cat "$projKeyFile")"
 	else
-		printf "%b\n" "$(inColor 1 'Bitbucket Project Key file not defined')"
-		printf "%b\n" "$(inColor 4 'You can get the key for a project at https://bitbucket.org/dashboard/projects')"
-		printf "%b\n" "$(inColor 4 'The new repo will be created in the provided project')"
+		printf "%b\n" "$(inColor 1 'Bitbucket Project Key file not defined')" >&2
+		printf "%b\n" "$(inColor 4 'You can get the key for a project at https://bitbucket.org/dashboard/projects')" >&2
+		printf "%b\n" "$(inColor 4 'The new repo will be created in the provided project')" >&2
 
-		okinput=0
+		okInput=0
 		answer=""
-		while [ $okinput -eq 0 ]; do
-			printf "%b" "$(inColor 1 'Enter the project key: ')" 
+		while [ $okInput -eq 0 ]; do
+			printf "%b" "$(inColor 4 'Enter the project key: ')" >&2
 			read -r projectKey
 			ask "answer" "Project Key: $(inColor 1 "$projectKey")\nConfirm?"
-			[ "$answer" = "y" ] && okinput=1;
+			[ "$answer" = "y" ] && okInput=1;
 		done
+
 		echo "$projectKey" > "$projKeyFile"
 	fi
 	
@@ -357,13 +428,13 @@ createGitlabRepo() {
 }
 
 createRepos() {
-	command -v gpg > /dev/null 2>&1 || printf "%b\n" "$(inColor 1 'You need gpg (GnuPG) installed to create remote repos')" && exit 1 
+	command -v gpg > /dev/null 2>&1 || printf "%b\n" "$(inColor 1 'You need gpg (GnuPG) installed to create remote repos')" >&2 && exit 1 
 	checkRemotes
 
 	umask 0077
 	
 	[ -d "$configDir" ] || {
-		printf "Creating mahgits config directory at %s\n" "$configDir" >&2
+		printf "Creating mahgits config directory at %s\n" "$configDir"
 		mkdir -p "$configDir"
 	}	
 
@@ -374,13 +445,13 @@ createRepos() {
 		command -v vim > /dev/null 2>&1 && vim "$authFile" || nano "$authFile"
 		answer=""	
 		ask "answer" "Proceed to encrypt the tokens file '$authFile' ?"
-		[ "$answer" = "n" ] && echo "Aborting..." && exit 1
-		printf "%b\n" "\033[5;31mThis passphrase will be used to encrypt the tokens file\033[0m"
+		[ "$answer" = "n" ] && printf "Aborting...\n" >&2 && exit 1
+		printf "%b\n" "\033[5;31mThis passphrase will be used to encrypt the tokens file\033[0m" >&2 
 		sleep 4
 		if gpg -c "$authFile"; then
 			mv "$authFile.gpg" "$authFile"
 		else
-			printf "Failed to encrypt file\nAborting...\n" && exit 1
+			printf "Failed to encrypt file\nAborting...\n" >&2 && exit 1
 		fi
 	fi
 	
@@ -391,9 +462,10 @@ createRepos() {
 		[ "$answer" = "y" ] && {
 			echo RELOADAGENT | gpg-connect-agent
 			if ! tokens="$(gpg -d "$authFile" 2> /dev/null)"; then
-				printf "Failed to decrypt file\n%b\n" "$(inColor 1 'Aborting...')"
+				printf "Failed to decrypt file\n%b\n" "$(inColor 1 'Aborting...')" >&2
 				exit 1
 			fi
+			printf "File decrypted\n"
 		} || exit 1
 	fi
 
@@ -423,24 +495,23 @@ createRepos() {
 }
 
 run() {
-	
-	[ -d ".git" ] || {
-		printf "Not in a git directory.\nExiting...\n" >&2 
+	if ! git status > /dev/null 2>&1; then
+		printf "Not in a git directory\nExiting...\n" >&2 
 		exit 1
-	}
+	fi
 
-	chechSSHAgent
-	[ "$isInit" -eq 1 ] && initRemotes
+	curRemotes="$(git remote show)"
+	remoteNames="$(getRemoteNames)"
+	[ "$isInit" -eq 1 ] && initRemotes && exit 0
 	[ "$pushAll" -eq 1 ] && pushAllBranches && exit 0
 	[ "$pushOne" -eq 1 ] && pushOneBranch && exit 0
 	[ "$createRepos" -eq 1 ] && createRepos && exit 0
 	
 	pushBranches && exit 0
-
 }
 
 # check quotting
-if ! ARGS="$(getopt -n "mahgits" -o ab:fhr -l init,create -- "$@")"; then
+if ! ARGS="$(getopt -n "mahgits" -o ab:fhru -l init,create -- "$@")"; then
 	usage
 	exit 1
 fi
@@ -451,6 +522,7 @@ while : ; do
 		-a) pushAll=1; shift ;;
 		-b) pushOne=1; branchToPush="$2"; shift 2 ;;
 		-f) force=1; shift ;;
+		-u) uniqueUser=1; shift ;;
 		-h) usage; exit 0 ;;
 		-r) rRemotes=1; shift ;;
 		--init) isInit=1; shift ;;
